# Generated by Django 5.2.6 on 2025-09-16 17:18

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filemetadata_fileshare_fileaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerevision',
            name='file_data',
            field=models.FileField(upload_to=apps.files.models.user_file_path),
        ),
    ]
